# Generated by Django 4.0.3 on 2022-05-25 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='passord',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='login',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
