# Generated by Django 4.0.3 on 2022-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perguntas', '0002_rename_ativo_pergunta_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='answer',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='question',
            field=models.CharField(max_length=5000),
        ),
    ]
