# Generated by Django 4.0.3 on 2022-05-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('code_user', models.CharField(max_length=15)),
                ('ativo', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('cel', models.CharField(max_length=15)),
                ('telfixo', models.CharField(max_length=10)),
                ('cep', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=5)),
                ('nomecurso', models.CharField(max_length=200)),
                ('iniciocursoano', models.IntegerField(verbose_name=10)),
                ('simestreatual', models.IntegerField(verbose_name=50)),
                ('ensino_medio', models.IntegerField(verbose_name=50)),
                ('trabalha', models.IntegerField()),
                ('filhos', models.IntegerField()),
                ('possuinotbook', models.IntegerField()),
                ('obs', models.CharField(max_length=200)),
            ],
        ),
    ]
